! DESCRIP.MMS - build flex for OpenVMS (IA64, x86-64)
!
! Run from the top of the prepared source tree via [.VMS]BUILD.COM, which
! passes ARCH (IA64 or X86_64) and creates the output directories.  Source
! lists and per-object rules come from [.VMS]SOURCES.MMS, generated by
! tools/prepare.sh on the host.

.IFDEF ARCH
.ELSE
ARCH = IA64
.ENDIF

OBJ = [.OBJ_$(ARCH)]
LOBJ = [.OBJ_$(ARCH).LIB]
BIN = [.BIN_$(ARCH)]

.INCLUDE [.VMS]SOURCES.MMS

LIB = $(OBJ)LIBFL.OLB
EXE = $(BIN)FLEX.EXE

CC = CC
CFLAGS = $(CC_QUAL)/NOLIST/INCLUDE_DIRECTORY=("./src","./vms","PCRE2$ROOT:[INCLUDE]")-
	/DEFINE=($(CC_DEFS),HAVE_CONFIG_H)

! LIBFL.OLB is flex's runtime library for lex programs (yywrap, main),
! installed by the kit; flex itself does not link it.
ALL : $(EXE), $(LIB)
	@ CONTINUE

! "-": LINK ends with a warning status (%ILINK-W-COMPWARN) when modules
! compiled with VSI C's benign warnings; tools/build.sh fails the build on
! real link errors and undefined symbols.
! POSIX regex from PCRE2 (vms/regex.h): PCRE2$ROOT is the vms-pcre2 install tree.
$(EXE) : $(SRC_OBJS), $(EXTRA_OBJS)
	- LINK/EXECUTABLE=$(MMS$TARGET)/MAP=$(OBJ)FLEX.MAP/FULL $(SRC_OBJS), $(EXTRA_OBJS), -
	PCRE2$ROOT:[LIB]PCRE2-POSIX.OLB/LIBRARY, PCRE2$ROOT:[LIB]PCRE2-8.OLB/LIBRARY

$(LIB) : $(LIB_OBJS)
	IF F$SEARCH("$(MMS$TARGET)") .EQS. "" THEN LIBRARY/CREATE/OBJECT $(MMS$TARGET)
	LIBRARY/REPLACE/OBJECT $(MMS$TARGET) $(LOBJ)*.OBJ

CLEAN :
	IF F$SEARCH("$(LOBJ)*.*") .NES. "" THEN DELETE/NOLOG $(LOBJ)*.*;*
	IF F$SEARCH("$(OBJ)*.OBJ") .NES. "" THEN DELETE/NOLOG $(OBJ)*.OBJ;*,*.OLB;*,*.MAP;*
	IF F$SEARCH("$(BIN)*.*") .NES. "" THEN DELETE/NOLOG $(BIN)*.*;*
